
version: '3.8'

services:
  orchestrator:
    build:
      context: .
    container_name: orchestrator
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - MONGO_URI=mongodb://mongo:27017/
      - PYTHONUNBUFFERED=1
      - HEARTBEAT_INTERVAL=5
    depends_on:
      - mongo
    networks:
      - app_network

  agent:
    build:
      context: ../selenium-framework-agent
    container_name: agent
    ports:
      - "9000:9000"
    volumes:
      - ../selenium-framework-agent:/app
    environment:
      - ORCHESTRATOR_URL=http://orchestrator:8000
      - AGENT_ID=agent-1
      - PYTHONUNBUFFERED=1
      - AGENT_URL=http://agent:9000
      - HEARTBEAT_INTERVAL=5
    depends_on:
      - orchestrator
    networks:
      - app_network

  mongo:
    image: mongo:4.4
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network

volumes:
  mongo_data:

networks:
  app_network:
    driver: bridge